/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Rizza
 */
public class mainMenu extends javax.swing.JPanel {

    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenuEditStasiun = new javax.swing.JButton();
        btnMenuEditKereta = new javax.swing.JButton();
        btnMenuEditRute = new javax.swing.JButton();
        btnMenuBuatTiket = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txLabelMainMenu = new javax.swing.JLabel();

        setToolTipText("Menu Utama");
        setName("Menu Utama"); // NOI18N

        btnMenuEditStasiun.setText("Edit Data Stasiun");
        btnMenuEditStasiun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEditStasiunActionPerformed(evt);
            }
        });

        btnMenuEditKereta.setText("Edit Data Kereta");

        btnMenuEditRute.setText("Edit Data Rute");

        btnMenuBuatTiket.setText("Buat Tiket Perjalanan");

        btnExit.setText("Exit");

        txLabelMainMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txLabelMainMenu.setText("Menu Utama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenuBuatTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenuEditRute, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenuEditKereta, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenuEditStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txLabelMainMenu)
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txLabelMainMenu)
                .addGap(11, 11, 11)
                .addComponent(btnMenuEditStasiun)
                .addGap(18, 18, 18)
                .addComponent(btnMenuEditKereta)
                .addGap(18, 18, 18)
                .addComponent(btnMenuEditRute)
                .addGap(18, 18, 18)
                .addComponent(btnMenuBuatTiket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuEditStasiunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEditStasiunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuEditStasiunActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMenuBuatTiket;
    private javax.swing.JButton btnMenuEditKereta;
    private javax.swing.JButton btnMenuEditRute;
    private javax.swing.JButton btnMenuEditStasiun;
    private javax.swing.JLabel txLabelMainMenu;
    // End of variables declaration//GEN-END:variables

    public Object getBtnExit() {
        return btnExit;
    }

    public Object getBtnMenuBuatTiket() {
        return btnMenuBuatTiket;
    }
    
    public Object getBtnMenuEditKereta() {
        return btnMenuEditKereta;
    }

    public Object getBtnMenuEditRute() {
        return btnMenuEditRute;
    }

    public Object getBtnMenuEditStasiun() {
        return btnMenuEditStasiun;
    }

    public void addListener (ActionListener e) {
        btnExit.addActionListener(e);
        btnMenuBuatTiket.addActionListener(e);
        btnMenuEditKereta.addActionListener(e);
        btnMenuEditRute.addActionListener(e);
        btnMenuEditStasiun.addActionListener(e);
    }
    
}
