/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Gerbong;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author Rizza
 */
public class menuTambahGerbongKereta extends javax.swing.JPanel {

    /**
     * Creates new form menuTambahGerbongKereta
     */
    public menuTambahGerbongKereta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGerbong = new javax.swing.JTable();
        btnSelesai = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tambahkan Gerbong");

        tableGerbong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Jenis Gerbong", "Kapasitas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableGerbong.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableGerbong.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableGerbong);
        tableGerbong.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tableGerbong.getColumnModel().getColumnCount() > 0) {
            tableGerbong.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableGerbong.getColumnModel().getColumn(1).setPreferredWidth(180);
            tableGerbong.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        btnSelesai.setText("Selesai");

        btnTambah.setText("Tambahkan");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTambah.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                btnTambahCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                btnTambahInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelesai)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(btnTambah))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnTambahInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahInputMethodTextChanged

    private void btnTambahCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnTambahCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahCaretPositionChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableGerbong;
    // End of variables declaration//GEN-END:variables

    public Object getBtnSelesai() {
        return btnSelesai;
    }

    public Object getBtnTambah() {
        return btnTambah;
    }

    public int getSelectedGerbong() {
        return (int) tableGerbong.getValueAt(tableGerbong.getSelectedRow(), 0);
    }
    
    public void setGerbongData(List<Gerbong> list) {
        for (int i = 0; i < list.size(); i++) {
            tableGerbong.setValueAt(list.get(i).getIdGerbong(), i, 0);
            tableGerbong.setValueAt(list.get(i).getJenisGerbong(), i, 1);
            tableGerbong.setValueAt(list.get(i).getKapasitas(), i, 2);
        }
    }
    
    public void addListener (ActionListener e) {
        btnSelesai.addActionListener(e);
        btnTambah.addActionListener(e);
    }
    
    public void addAdapter (MouseAdapter e) {
        tableGerbong.addMouseListener(e);
    }

}
