/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Rute;
import Model.Stasiun;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Rizza
 */
public class menuEditRuteDetil extends javax.swing.JPanel {

    /**
     * Creates new form menuAddRute
     */
    public menuEditRuteDetil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txFieldNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comBoxSt1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comBoxSt2 = new javax.swing.JComboBox<>();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txFieldJmlKereta = new javax.swing.JTextField();
        btnEditDaftarKereta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txFieldJmlTiket = new javax.swing.JTextField();
        btnViewTiket = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Data Rute");

        jLabel2.setText("Nama Rute");

        txFieldNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setText("Stasiun 1");

        jLabel4.setText("Stasiun 2");

        btnBatal.setText("Batal");

        btnSimpan.setText("Tambahkan");

        jLabel5.setText("Jumlah Kereta");

        txFieldJmlKereta.setEditable(false);

        btnEditDaftarKereta.setText("Edit Daftar Kereta");

        jLabel6.setText("Jumlah Tiket");

        txFieldJmlTiket.setEditable(false);

        btnViewTiket.setText("Lihat Daftar Tiket");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txFieldNama)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(comBoxSt1, 0, 153, Short.MAX_VALUE)
                                        .addComponent(comBoxSt2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txFieldJmlTiket, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                            .addComponent(txFieldJmlKereta))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnEditDaftarKereta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnViewTiket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comBoxSt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comBoxSt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txFieldJmlKereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditDaftarKereta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txFieldJmlTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewTiket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEditDaftarKereta;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnViewTiket;
    private javax.swing.JComboBox<String> comBoxSt1;
    private javax.swing.JComboBox<String> comBoxSt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txFieldJmlKereta;
    private javax.swing.JTextField txFieldJmlTiket;
    private javax.swing.JTextField txFieldNama;
    // End of variables declaration//GEN-END:variables

    public void setTxFieldNama(Rute r) {
        txFieldNama.setText(r.getNamaRute());
    }
    
    public void setTxFieldJmlKereta(int n) {
        txFieldJmlKereta.setText(String.valueOf(n));
    }
    
    public void setTxFieldJmlTiket(int n) {
        txFieldJmlTiket.setText(String.valueOf(n));
    }
    
    public void setComBoxSt(List<Stasiun> list) {
        for (int i = 0; i < list.size(); i++) {
            comBoxSt1.addItem(list.get(i).getNamaStasiun());
            comBoxSt2.addItem(list.get(i).getNamaStasiun());
        }
    }

    public Object getBtnBatal() {
        return btnBatal;
    }

    public Object getBtnSimpan() {
        return btnSimpan;
    }
    
    public Object getBtnEditDaftarKereta() {
        return btnEditDaftarKereta;
    }
    
    public Object getBtnViewTiket() {
        return btnViewTiket;
    }

    public int getComBoxSt1() {
        return comBoxSt1.getSelectedIndex();
    }

    public int getComBoxSt2() {
        return comBoxSt2.getSelectedIndex();
    }

    public String getTxFieldNama() {
        return txFieldNama.getText();
    }
    
    public void addListener (ActionListener e) {
        btnBatal.addActionListener(e);
        btnSimpan.addActionListener(e);
        btnEditDaftarKereta.addActionListener(e);
        btnViewTiket.addActionListener(e);
        comBoxSt1.addActionListener(e);
        comBoxSt2.addActionListener(e);
    }
    
}
