/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Gerbong;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Rizza
 */
public class menuCreateTiket3 extends javax.swing.JPanel {

    /**
     * Creates new form menuEditGerbong2
     */
    public menuCreateTiket3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGerbong = new javax.swing.JTable();
        btnSelesai = new javax.swing.JButton();
        btnBuat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buat Tiket Perjalanan");

        tableGerbong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Jenis Gerbong", "Kapasitas", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableGerbong.setColumnSelectionAllowed(true);
        tableGerbong.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableGerbong);
        tableGerbong.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tableGerbong.getColumnModel().getColumnCount() > 0) {
            tableGerbong.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableGerbong.getColumnModel().getColumn(1).setPreferredWidth(160);
            tableGerbong.getColumnModel().getColumn(2).setPreferredWidth(50);
            tableGerbong.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        btnSelesai.setText("Selesai");

        btnBuat.setText("Buat");

        jLabel2.setText("Silahkan Pilih Gerbong yang Akan Dibuat Tiketnya lalu klik 'Buat'");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBuat)
                            .addGap(18, 18, 18)
                            .addComponent(btnSelesai))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(btnBuat))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuat;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableGerbong;
    // End of variables declaration//GEN-END:variables

    public Object getBtnSelesai() {
        return btnSelesai;
    }

    public Object getBtnBuat() {
        return btnBuat;
    }
    public int getTableGerbong() {
        return (int) tableGerbong.getValueAt(tableGerbong.getSelectedRow(), 0);
    }
    
    public void setTableGerbong(List<Gerbong> list) {
        tableGerbong.clearSelection();
        for (int i = 0; i < tableGerbong.getRowCount(); i++) {
            tableGerbong.setValueAt("", i, 0);
            tableGerbong.setValueAt("", i, 1);
            tableGerbong.setValueAt("", i, 2);
            tableGerbong.setValueAt("", i, 3);
        }
        for (int i = 0; i < list.size(); i++) {
            tableGerbong.setValueAt(list.get(i).getIdGerbong(), i, 0);
            tableGerbong.setValueAt(list.get(i).getJenisGerbong(), i, 1);
            tableGerbong.setValueAt(list.get(i).getKapasitas(), i, 2);
            tableGerbong.setValueAt(list.get(i).getJmlGerbong(), i, 3);
        }
    }    

    public void addListener (ActionListener e) {
        btnSelesai.addActionListener(e);
        btnBuat.addActionListener(e);
    }
    
    public void addAdapter (MouseAdapter e) {
        tableGerbong.addMouseListener(e);
    }
    
}
