/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Rizza
 */
public class menuEditStasiun extends javax.swing.JPanel {

    /**
     * Creates new form menuEditStasiun
     */
    public menuEditStasiun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txLabelMenuEditStasiun = new javax.swing.JLabel();
        btnTambahStasiun = new javax.swing.JButton();
        btnEditStasiun = new javax.swing.JButton();
        btnBacktoMainMenu = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txLabelMenuEditStasiun.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txLabelMenuEditStasiun.setText("Menu Edit Stasiun");

        btnTambahStasiun.setText("Tambahkan Stasiun Baru");

        btnEditStasiun.setText("Edit Data Stasiun yang Ada");

        btnBacktoMainMenu.setText("Kembali ke Menu Utama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txLabelMenuEditStasiun)
                    .addComponent(btnTambahStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBacktoMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txLabelMenuEditStasiun)
                .addGap(43, 43, 43)
                .addComponent(btnTambahStasiun)
                .addGap(18, 18, 18)
                .addComponent(btnEditStasiun)
                .addGap(52, 52, 52)
                .addComponent(btnBacktoMainMenu)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBacktoMainMenu;
    private javax.swing.JButton btnEditStasiun;
    private javax.swing.JButton btnTambahStasiun;
    private javax.swing.JLabel txLabelMenuEditStasiun;
    // End of variables declaration//GEN-END:variables

    public Object getBtnBacktoMainMenu() {
        return btnBacktoMainMenu;
    }

    public Object getBtnEditStasiun() {
        return btnEditStasiun;
    }

    public Object getBtnTambahStasiun() {
        return btnTambahStasiun;
    }
    
    public void addListener (ActionListener e) {
        btnBacktoMainMenu.addActionListener(e);
        btnEditStasiun.addActionListener(e);
        btnTambahStasiun.addActionListener(e);
    }

}
