/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.*;
import java.awt.event.ActionListener;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author Rizza
 */
public class menuEditStasiunDetil extends javax.swing.JPanel {
    Application app;
    List<Stasiun> daftarStasiun = new ArrayList<>();

    public menuEditStasiunDetil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txLabelNoStasiun = new javax.swing.JLabel();
        txFieldNoStasiun = new javax.swing.JTextField();
        txFieldNamaStasiun = new javax.swing.JTextField();
        txLabelNamaStasiun = new javax.swing.JLabel();
        txLabelSingkatan = new javax.swing.JLabel();
        txFieldSingkatan = new javax.swing.JTextField();
        txFieldAlamat = new javax.swing.JTextField();
        txLabelAlamat = new javax.swing.JLabel();
        txLabelKota = new javax.swing.JLabel();
        txFieldKota = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Edit Stasiun");

        txLabelNoStasiun.setText("Nomor Stasiun");

        txFieldNoStasiun.setEditable(false);
        txFieldNoStasiun.setToolTipText("");

        txLabelNamaStasiun.setText("Nama Stasiun");

        txLabelSingkatan.setText("Singkatan");

        txFieldAlamat.setPreferredSize(new java.awt.Dimension(6, 50));

        txLabelAlamat.setText("Alamat");

        txLabelKota.setText("Kota");

        btnCancel.setText("Cancel");

        btnOk.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOk)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txLabelNoStasiun)
                            .addComponent(txLabelNamaStasiun)
                            .addComponent(txLabelSingkatan)
                            .addComponent(txLabelAlamat)
                            .addComponent(txLabelKota))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txFieldKota, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFieldSingkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFieldNamaStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFieldNoStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldNoStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txLabelNoStasiun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txLabelNamaStasiun)
                    .addComponent(txFieldNamaStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldSingkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txLabelSingkatan))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txFieldAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txFieldKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txLabelKota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnOk))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txLabelAlamat)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txFieldAlamat;
    private javax.swing.JTextField txFieldKota;
    private javax.swing.JTextField txFieldNamaStasiun;
    private javax.swing.JTextField txFieldNoStasiun;
    private javax.swing.JTextField txFieldSingkatan;
    private javax.swing.JLabel txLabelAlamat;
    private javax.swing.JLabel txLabelKota;
    private javax.swing.JLabel txLabelNamaStasiun;
    private javax.swing.JLabel txLabelNoStasiun;
    private javax.swing.JLabel txLabelSingkatan;
    // End of variables declaration//GEN-END:variables

    public Object getBtnCancel() {
        return btnCancel;
    }

    public Object getBtnOk() {
        return btnOk;
    }

    public String getTxFieldAlamat() {
        return txFieldAlamat.getText();
    }

    public String getTxFieldKota() {
        return txFieldKota.getText();
    }

    public String getTxFieldNamaStasiun() {
        return txFieldNamaStasiun.getText();
    }

    public String getTxFieldSingkatan() {
        return txFieldSingkatan.getText();
    }
    
    public int getTxFieldNoStasiun() {
        return Integer.parseInt(txFieldNoStasiun.getText());
    }
    
    public void setComponent(Stasiun s) {
        txFieldNoStasiun.setText(String.valueOf(s.getNomorStasiun()));
        txFieldNamaStasiun.setText(s.getNamaStasiun());
        txFieldSingkatan.setText(s.getSingkatan());
        txFieldAlamat.setText(s.getAlamat());
        txFieldKota.setText(s.getKota());
    }

    public void addListener(ActionListener e) {
        txFieldAlamat.addActionListener(e);
        txFieldKota.addActionListener(e);
        txFieldNamaStasiun.addActionListener(e);
        txFieldNoStasiun.addActionListener(e);
        txFieldSingkatan.addActionListener(e);
        btnCancel.addActionListener(e);
        btnOk.addActionListener(e);
    }
    
}
