/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author Rizza
 */
public class menuAddStasiun extends javax.swing.JPanel {

    /**
     * Creates new form menuAddStasiun
     */
    public menuAddStasiun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txLabelTambahStasiun = new javax.swing.JLabel();
        txLabelNoStasiun = new javax.swing.JLabel();
        txFieldNoStasiun = new javax.swing.JTextField();
        txLabelNamaStasiun = new javax.swing.JLabel();
        txFieldNamaStasiun = new javax.swing.JTextField();
        txLabelSingkatan = new javax.swing.JLabel();
        txFieldSingkatan = new javax.swing.JTextField();
        txLabelAlamat = new javax.swing.JLabel();
        txFieldAlamat = new javax.swing.JTextField();
        txLabelKota = new javax.swing.JLabel();
        txFieldKota = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        txLabelTambahStasiun.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txLabelTambahStasiun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txLabelTambahStasiun.setText("Tambahkan Data Stasiun Baru");

        txLabelNoStasiun.setLabelFor(txFieldNoStasiun);
        txLabelNoStasiun.setText("Nomor Stasiun");

        txFieldNoStasiun.setToolTipText("");
        txFieldNoStasiun.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txFieldNoStasiunInputMethodTextChanged(evt);
            }
        });

        txLabelNamaStasiun.setLabelFor(txFieldNamaStasiun);
        txLabelNamaStasiun.setText("Nama Stasiun");

        txLabelSingkatan.setLabelFor(txLabelSingkatan);
        txLabelSingkatan.setText("Singkatan");

        txLabelAlamat.setLabelFor(txLabelAlamat);
        txLabelAlamat.setText("Alamat");

        txFieldAlamat.setPreferredSize(new java.awt.Dimension(6, 50));

        txLabelKota.setLabelFor(txFieldKota);
        txLabelKota.setText("Kota");

        btnOk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOk.setText("OK");

        btnBatal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBatal.setText("Batal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txLabelTambahStasiun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txLabelSingkatan)
                    .addComponent(txLabelNamaStasiun)
                    .addComponent(txLabelAlamat)
                    .addComponent(txLabelKota)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnOk)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txLabelNoStasiun)
                                .addGap(18, 18, 18)
                                .addComponent(txFieldNoStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFieldNamaStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFieldSingkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFieldKota, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txLabelTambahStasiun)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txLabelNoStasiun)
                    .addComponent(txFieldNoStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txLabelNamaStasiun)
                    .addComponent(txFieldNamaStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txLabelSingkatan)
                    .addComponent(txFieldSingkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(txLabelAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txLabelKota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnOk))
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txFieldNoStasiunInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txFieldNoStasiunInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNoStasiunInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnOk;
    private javax.swing.JTextField txFieldAlamat;
    private javax.swing.JTextField txFieldKota;
    private javax.swing.JTextField txFieldNamaStasiun;
    private javax.swing.JTextField txFieldNoStasiun;
    private javax.swing.JTextField txFieldSingkatan;
    private javax.swing.JLabel txLabelAlamat;
    private javax.swing.JLabel txLabelKota;
    private javax.swing.JLabel txLabelNamaStasiun;
    private javax.swing.JLabel txLabelNoStasiun;
    private javax.swing.JLabel txLabelSingkatan;
    private javax.swing.JLabel txLabelTambahStasiun;
    // End of variables declaration//GEN-END:variables

    public String getTxFieldAlamat() {
        return txFieldAlamat.getText();
    }

    public void setTxFieldAlamat(String input) {
        txFieldAlamat.setText(input);
    }

    public String getTxFieldKota() {
        return txFieldKota.getText();
    }

    public void setTxFieldKota(String input) {
        this.txFieldKota.setText(input);
    }

    public String getTxFieldNamaStasiun() {
        return txFieldNamaStasiun.getText();
    }

    public void setTxFieldNamaStasiun(String input) {
        this.txFieldNamaStasiun.setText(input);
    }

    public int getTxFieldNoStasiun() {
        return Integer.parseInt(txFieldNoStasiun.getText());
    }

    public void setTxFieldNoStasiun(int input) {
        this.txFieldNoStasiun.setText(String.valueOf(input));
    }

    public String getTxFieldSingkatan() {
        return txFieldSingkatan.getText();
    }

    public void setTxFieldSingkatan(String input) {
        this.txFieldSingkatan.setText(input);
    }

    public Object getBtnBatal() {
        return btnBatal;
    }

    public Object getBtnOk() {
        return btnOk;
    }

    public void addListener (ActionListener e) {
        txFieldAlamat.addActionListener(e);
        txFieldKota.addActionListener(e);
        txFieldNamaStasiun.addActionListener(e);
        txFieldNoStasiun.addActionListener(e);
        txFieldSingkatan.addActionListener(e);
        btnOk.addActionListener(e);
        btnBatal.addActionListener(e);
    }
       
}
